site_name: C语言生存手册
site_description: 探索C语言的广度与深度——从语法到系统编程。
site_author: tink
site_url: https://clang.cyub.vip
strict: false

# Copyright
copyright: Copyright &copy; 2024 Tink

# Configuration
theme:
  name: material
  language: zh
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    # - content.code.select
    - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - navigation.expand
    - navigation.footer
    # - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    # - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font: false
  favicon: images/favicon.png
  icon:
    logo: logo

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - git-revision-date-localized:
      type: iso_date
      enable_creation_date: true
  - mkdocs-jupyter:
      include: ["*.ipynb"]
  - glightbox
  - git-committers:
      repository: cyub/read-notes
      branch: main
  - markmap
  - rss:
      length: 1000
      use_git: true
      feeds_filenames:
        json_created: feed.json
        json_updated: feed-updated.json
        rss_created: feed.xml
        rss_updated: feed-updated.xml

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: fontawesome/solid/blog
      link: https://www.cyub.vip
      name: 个人博客
    - icon: fontawesome/brands/golang
      link: https://go.cyub.vip
      name: 《深入Go语言之旅》
    - icon: fontawesome/brands/github
      link: https://github.com/cyub
      name: 个人Github
    - icon: material/rss
      link: /feed.xml
      name: RSS Feed

# extra_css:
#   - "css/extra.css"
#   - "https://cdn.jsdelivr.net/npm/roboto-font@0.1.0/css/fonts.min.css"
#   - "https://cdn.jsdelivr.net/npm/typeface-roboto-mono@1.1.13/index.css"

extra_css:
    - "css/extra.css"
    - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
# extra_javascript:
#   - javascripts/mathjax.js
#   - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      normalize_issue_symbols: true
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      combine_header_slug: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - 首页: /
  - 基础知识:
    - 简介: basic/clang_intro.md
    - 开发环境搭建: basic/dev_env.md
    - 程序结构: basic/prog_structure.md
    - 数据类型与变量: basic/clang_var.md
  - 高级特性:
    - 命令行参数解析: feature/cmdline_option.md
  - Libuv入门:
    - 简介: libuv/简介.md
    - 设计思想: libuv/设计思想.md
    - 文件系统: libuv/文件系统.md
    - 网络编程: libuv/网络编程.md
